name: TWRP - Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'TWRP Manifest Branch'
        required: true
        default: 'twrp-12.1'
        type: choice
        options:
        - twrp-12.1
        - twrp-11
      DEVICE_TREE:
        description: 'TWRP Device Tree'
        required: true
        default: 'https://github.com/galaxy-a16/android_device_samsung_a16'
      COMMON_TREE:
        description: 'Device Common Tree'
        required: false
        default: 'https://github.com/galaxy-a16/android_device_samsung_mt6835-common'
      KERNEL_TREE:
        description: 'Device Kernel Tree (NOT NEEDED IF YOU ARE NOT BUILDING MI439, YOU CAN LEAVE IT BLANK.)'
        required: false
        default: 'https://github.com/Mi-Thorium/android_device_xiaomi_kernel-mithorium'
      KERNEL_PATH:
        description: 'Device Kernel Tree Path (LEAVE IT BLANK IF YOU LEAVED KERNEL TREE BLANK TOO.)'
        required: false
        default: 'device/xiaomi/kernel-mithorium'
      COMMON_PATH:
        description: 'Device Common Tree Path'
        required: false
        default: 'device/samsung/mt6835-common'
      DEVICE_TREE_BRANCH:
        description: 'TWRP Device Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_PATH:
        description: 'Specify your Device Path'
        required: true
        default: 'device/samsung/a16'
      DEVICE_NAME:
        description: 'Specify your Device Codename'
        required: true
        default: 'a16'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: Build TWRP by ${{ github.actor }}
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
              
    - name: Free disk space (1/1)
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 repo

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Setup Manifest and Sync TWRP
      if: inputs.MANIFEST_BRANCH == 'twrp-11' || inputs.MANIFEST_BRANCH == 'twrp-12.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/TWRP
        cd ${GITHUB_WORKSPACE}/TWRP
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b ${{ inputs.MANIFEST_BRANCH }}
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/TWRP
        git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ./${{ inputs.DEVICE_PATH }}
        cd ${{ inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Clone Common Tree
      run: |
        cd ${GITHUB_WORKSPACE}/TWRP
        git clone ${{ inputs.COMMON_TREE }} ./${{ inputs.COMMON_PATH }}
        cd ${{ inputs.COMMON_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Clone Kernel Tree
      if: ${{ inputs.KERNEL_TREE != '' }}
      run: |
        cd ${GITHUB_WORKSPACE}/TWRP
        git clone ${{ inputs.KERNEL_TREE }} ./${{ inputs.KERNEL_PATH }}

    - name: Apply patches
      run: |
        export MANIFEST_BRANCH=${{ inputs.MANIFEST_BRANCH }}
        export DEVICE_PATH=${{ inputs.DEVICE_PATH }}
        bash patch-maintainer.sh

    - name: Apply kernel header patches if building on Mi439
      if: ${{ inputs.KERNEL_TREE != '' }}
      run: |
        sed -i 's/name: "generated_kernel_headers"/name: "generated_kernel_headers_twrp"/' vendor/twrp/build/soong/Android.bp

    - name: Building TWRP
      run: |
        cd ${GITHUB_WORKSPACE}/TWRP
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        set -e
        lunch twrp_${{ inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ inputs.BUILD_TARGET }}image
        
    - name: Set Release Properties
      run: |
        echo "BUILD_DATE=$(TZ=Asia/Manila date +'%d %B %Y %H:%M')" >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/TWRP
        DEVICE_TREE_URL="${{ inputs.DEVICE_TREE }}"
        if [[ "${DEVICE_TREE_URL}" == *.git ]]; then
          DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
        fi
        echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${GITHUB_WORKSPACE}/TWRP/out/target/product/${{ inputs.DEVICE_NAME }}/*.img
        name: TWRP Recovery for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## TWRP Recovery Build - Unofficial
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ env.DEVICE_TREE_URL }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ env.DEVICE_TREE_URL }}/commit/${{ env.COMMIT_ID }}) during building.
